/**
 * AdoptionIsProblem - Step 1, Thing 3
 * Full-width layout with two columns: problem explanation + statistics
 * 
 * ⚠️ Props should be generated by Runtime Agent from tele-knowledge.md
 */
import React from 'react';
import { AlertTriangle, X, ArrowRight, LucideIcon } from 'lucide-react';
import * as LucideIcons from 'lucide-react';
import { notifyTele } from '@/utils/acknowledgmentHelpers';
import { useSound } from '@/hooks/useSound';

interface ProblemItem {
    icon?: string;
    text: string;
}

interface StatItem {
    icon?: string;
    value: string;
    label: string;
}

interface AdoptionIsProblemProps {
    headline?: string;
    subheadline?: string;
    problems?: ProblemItem[];
    conclusion?: string;
    stats?: StatItem[];
    ctaLabel?: string;
    ctaActionPhrase?: string;
}

const getIcon = (iconName?: string): LucideIcon => {
    if (!iconName) return AlertTriangle;
    const icons = LucideIcons as unknown as Record<string, LucideIcon>;
    return icons[iconName] || AlertTriangle;
};

export const AdoptionIsProblem: React.FC<AdoptionIsProblemProps> = ({
    headline = "Adoption IS the Problem",
    subheadline = "There's no UI for AI",
    problems = [
        { icon: "HelpCircle", text: "Users don't know how to interact with AI" },
        { icon: "Users", text: "Training doesn't stick" },
        { icon: "Frown", text: "Frustration leads to abandonment" }
    ],
    conclusion = "The technology works. There's just no UI for AI.",
    stats = [
        { icon: "TrendingDown", value: "70%", label: "of AI projects never reach production" },
        { icon: "Users", value: "23%", label: "of employees use AI tools regularly" },
        { icon: "Clock", value: "6 mo", label: "average time to first value" },
    ],
    ctaLabel = "What's the solution?",
    ctaActionPhrase = "Show me what a tele is",
}) => {
    const { playClick } = useSound();
    const handleAction = (phrase: string) => { playClick(); notifyTele(phrase); };

    return (
        <div className="glass-template-container">
            <div className="grid md:grid-cols-2 gap-8">
                {/* Left Column - Problem Explanation */}
                <div className="p-8 rounded-xl bg-flamingo/10 border border-flamingo/30">
                    <div className="flex items-center gap-4 mb-6">
                        <div className="w-14 h-14 rounded-xl bg-flamingo/20 border border-flamingo/30 flex items-center justify-center">
                            <AlertTriangle className="w-7 h-7 text-flamingo" />
                        </div>
                        <div>
                            <h3 className="text-2xl font-bold text-white">{headline}</h3>
                            <p className="text-flamingo">{subheadline}</p>
                        </div>
                    </div>
                    <div className="space-y-4 mb-6">
                        {problems.map((item, i) => {
                            const IconComp = getIcon(item.icon);
                            return (
                                <div key={i} className="flex items-center gap-3">
                                    <IconComp className="w-5 h-5 text-flamingo flex-shrink-0" />
                                    <span className="text-mist/80">{item.text}</span>
                                </div>
                            );
                        })}
                    </div>
                    <p className="text-white font-semibold text-lg">{conclusion}</p>
                </div>

                {/* Right Column - Impact Stats */}
                <div className="space-y-6">
                    {stats.map((stat, i) => {
                        const IconComp = getIcon(stat.icon);
                        return (
                            <div key={i} className="p-6 rounded-xl bg-white/[0.04] border border-white/[0.08]">
                                <div className="flex items-center gap-4 mb-4">
                                    <div className="w-12 h-12 rounded-lg bg-flamingo/20 flex items-center justify-center">
                                        <IconComp className="w-6 h-6 text-flamingo" />
                                    </div>
                                    <div>
                                        <p className="text-3xl font-bold text-white">{stat.value}</p>
                                        <p className="text-mist/60">{stat.label}</p>
                                    </div>
                                </div>
                            </div>
                        );
                    })}
                    {ctaLabel && (
                        <button
                            className="w-full inline-flex items-center justify-center gap-2 px-6 py-4 bg-flamingo text-white font-semibold rounded-full hover:bg-flamingo/90 transition-all"
                            onClick={() => handleAction(ctaActionPhrase || '')}
                        >
                            {ctaLabel}
                            <ArrowRight className="w-4 h-4" />
                        </button>
                    )}
                </div>
            </div>
        </div>
    );
};
export default AdoptionIsProblem;
